In [6]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://artifact.intuit.com/artifactory/api/pypi/pypi-intuit/simple
Requirement already satisfied: pandas in /Users/aragothaman/Library/Python/3.13/lib/python/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/aragothaman/Library/Python/3.13/lib/python/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/aragothaman/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/aragothaman/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python3.13 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [9]:
cdf = pd.read_csv('data/covid/cases_deaths.csv')

In [13]:
cdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 579174 entries, 0 to 579173
Data columns (total 40 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   country                                  579174 non-null  str
 1   date                                     579174 non-null  str
 2   new_cases                                574898 non-null  float64
 3   total_cases                              579174 non-null  int64
 4   new_deaths                               576007 non-null  float64
 5   total_deaths                             579174 non-null  int64
 6   weekly_cases                             573643 non-null  float64
 7   weekly_deaths                            574762 non-null  float64
 8   weekly_pct_growth_cases                  347939 non-null  float64
 9   weekly_pct_growth_deaths                 219078 non-null  float64
 10  biweekly_cases                           571886 non-null  float64
 11  biweekly_deaths                          573017 non-null  float64
 12  biweekly_pct_growth_cases                364076 non-null  float64
 13  biweekly_pct_growth_deaths               240061 non-null  float64
 14  new_cases_per_million                    574898 non-null  float64
 15  new_deaths_per_million                   576007 non-null  float64
 16  total_cases_per_million                  579174 non-null  float64
 17  total_deaths_per_million                 579174 non-null  float64
 18  weekly_cases_per_million                 573643 non-null  float64
 19  weekly_deaths_per_million                574762 non-null  float64
 20  biweekly_cases_per_million               571886 non-null  float64
 21  biweekly_deaths_per_million              573017 non-null  float64
 22  total_deaths_per_100k                    579174 non-null  float64
 23  new_deaths_per_100k                      576007 non-null  float64
 24  new_cases_7_day_avg_right                573689 non-null  float64
 25  new_deaths_7_day_avg_right               574795 non-null  float64
 26  new_cases_per_million_7_day_avg_right    573689 non-null  float64
 27  new_deaths_per_million_7_day_avg_right   574795 non-null  float64
 28  new_deaths_per_100k_7_day_avg_right      574795 non-null  float64
 29  cfr                                      548973 non-null  float64
 30  cfr_100_cases                            525537 non-null  float64
 31  cfr_short_term                           306702 non-null  float64
 32  days_since_100_total_cases               567544 non-null  float64
 33  days_since_5_total_deaths                551262 non-null  float64
 34  days_since_1_total_cases_per_million     574522 non-null  float64
 35  days_since_0_1_total_deaths_per_million  560566 non-null  float64
 36  days_since_100_total_cases_and_5m_pop    316336 non-null  float64
 37  total_deaths_last12m                     79182 non-null   float64
 38  total_deaths_per_100k_last12m            79182 non-null   float64
 39  total_deaths_per_million_last12m         79182 non-null   float64
dtypes: float64(36), int64(2), str(2)
memory usage: 176.8 MB

In [10]:
cdf.describe()

,new_cases,total_cases,new_deaths,total_deaths,weekly_cases,weekly_deaths,weekly_pct_growth_cases,weekly_pct_growth_deaths,biweekly_cases,biweekly_deaths,...,cfr_100_cases,cfr_short_term,days_since_100_total_cases,days_since_5_total_deaths,days_since_1_total_cases_per_million,days_since_0_1_total_deaths_per_million,days_since_100_total_cases_and_5m_pop,total_deaths_last12m,total_deaths_per_100k_last12m,total_deaths_per_million_last12m
count,5.748980e+05,5.791740e+05,576007.000000,5.791740e+05,5.736430e+05,574762.000000,347939.000000,219078.000000,5.718860e+05,573017.000000,...,525537.000000,306702.000000,567544.000000,551262.000000,574522.000000,560566.000000,316336.000000,79182.000000,79182.000000,79182.000000
mean,9.460280e+03,1.495616e+07,90.470208,1.601894e+05,6.636634e+04,634.648722,32.116829,15.741258,1.331390e+05,1273.153882,...,1.633382,1.002247,990.340164,972.407173,1045.046559,995.794606,1071.102941,253.607373,0.143124,1.431242
std,1.111743e+05,7.636277e+07,762.193143,7.947452e+05,6.646479e+05,4914.224727,765.180457,488.857712,1.301131e+06,9812.523526,...,9.583963,1.583683,702.982289,703.836701,691.912999,701.559661,674.825611,1578.814617,0.942310,9.423099
min,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,-100.000000,-100.000000,0.000000e+00,0.000000,...,0.000000,0.000000,-1051.000000,-953.000000,-1074.000000,-1260.000000,-540.000000,0.000000,0.000000,0.000000
25%,0.000000e+00,1.018900e+04,0.000000,8.500000e+01,0.000000e+00,0.000000,-27.500000,-33.300000,0.000000e+00,0.000000,...,0.549878,0.000000,409.000000,391.000000,464.000000,414.000000,490.000000,0.000000,0.000000,0.000000
50%,0.000000e+00,9.239350e+04,0.000000,1.104000e+03,1.600000e+01,0.000000,-3.700000,-3.700000,3.900000e+01,0.000000,...,1.130243,0.305671,990.000000,972.000000,1045.000000,996.000000,1071.000000,0.000000,0.000000,0.000000
75%,3.300000e+01,1.153361e+06,0.000000,1.393100e+04,9.580000e+02,9.000000,23.600000,20.000000,1.983000e+03,19.000000,...,1.989497,1.405509,1578.000000,1557.000000,1633.000000,1584.000000,1653.000000,0.000000,0.000000,0.000000
max,8.401906e+06,7.791355e+08,57167.000000,7.114321e+06,4.481423e+07,103745.000000,120200.000000,125400.000000,7.335240e+07,205472.000000,...,2515.151515,10.000000,2310.000000,2312.000000,2321.000000,2299.000000,2310.000000,15932.000000,15.524599,155.245989

In [12]:
cdf.head()

cdf['country'].nunique()

249

In [3]:
df = pd.read_csv('data/world-happiness-report/2015.csv')

In [4]:
df.describe()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,79.493671,5.375734,0.047885,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296,2.098977
std,45.754363,1.145010,0.017146,0.403121,0.272369,0.247078,0.150693,0.120034,0.126685,0.553550
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580
25%,40.250000,4.526000,0.037268,0.545808,0.856823,0.439185,0.328330,0.061675,0.150553,1.759410
50%,79.500000,5.232500,0.043940,0.910245,1.029510,0.696705,0.435515,0.107220,0.216130,2.095415
75%,118.750000,6.243750,0.052300,1.158448,1.214405,0.811013,0.549092,0.180255,0.309883,2.462415
max,158.000000,7.587000,0.136930,1.690420,1.402230,1.025250,0.669730,0.551910,0.795880,3.602140

In [5]:
df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176